In [49]:
import pandas as pd
import numpy as np

In [50]:
methane_load = "resources/totalghge2.csv"
methane_data = pd.read_csv(methane_load)

In [51]:
methane_df = methane_data

In [52]:
methane_df.head()

,State,State abbreviation,FIPS State code,State nameplate capacity (MW),State annual heat input from combustion (MMBtu),State ozone season heat input from combustion (MMBtu),State total annual heat input (MMBtu),State total ozone season heat input (MMBtu),State annual net generation (MWh),State ozone season net generation (MWh),...,State wind generation percent (resource mix),State solar generation percent (resource mix),State geothermal generation percent (resource mix),State other fossil generation percent (resource mix),State other unknown/ purchased fuel generation percent (resource mix),State total nonrenewables generation percent (resource mix),State total renewables generation percent (resource mix),State total nonhydro renewables generation percent (resource mix),State total combustion generation percent (resource mix),State total noncombustion generation percent (resource mix)
0,x,PSTATABB,FIPSST,NAMEPCAP,STHTIAN,STHTIOZ,STHTIANT,STHTIOZT,STNGENAN,STNGENOZ,...,STWIPR,STSOPR,STGTPR,STOFPR,STOPPR,STTNPR,STTRPR,STTHPR,STCYPR,STCNPR
1,Alaska,AK,02,"3,439","42,553,081","16,236,971","59,433,354","22,529,498","6,335,034","2,406,057",...,2.7,0.0,0.0,0.0,0.0,70.4,29.5,3.4,71.1,28.9
2,Alabama,AL,01,"38,354","824,393,497","395,164,798","1,310,962,923","593,145,427","142,863,240","64,618,103",...,0.0,0.0,0.0,0.0,0.0,92.4,7.6,2.4,66.8,33.2
3,Arkansas,AR,05,"19,536","387,648,456","187,652,732","561,261,411","267,815,481","60,445,059","28,838,751",...,0.0,0.0,0.0,0.0,0.0,91.7,8.3,2.3,71.8,28.2
4,Arizona,AZ,04,"40,135","602,858,094","315,929,076","1,047,151,854","506,075,202","108,734,631","53,847,909",...,0.5,3.4,0.0,0.0,0.0,89.2,10.8,4.1,59.6,40.4

In [53]:
state_abrv = methane_df["State"]
state_greenhouse = methane_df["State nameplate capacity (MW)"]
state_emission = methane_df["State annual CH4 emissions (lbs)"]
state_co2 = methane_df["State annual CO2 emissions (tons)"]
state_biomass = methane_df["State annual biomass net generation (MWh)"]
state_transportation = methane_df["State annual total combustion net generation (MWh)"]



methane_data_df = pd.DataFrame({
    
    "State": state_abrv,
    "Tons of Greenhouse Gas Emissions": state_greenhouse,
    "Methane Emission": state_emission,
    "CO2 Emissions": state_co2,
    "State Biomass Generation": state_biomass,
    "State Transportation Generation": state_transportation
    
})


methane1_df = methane_data_df[["State", "Tons of Greenhouse Gas Emissions", "Methane Emission", "CO2 Emissions", "State Biomass Generation", "State Transportation Generation"]]
methane1_df.head()

,State,Tons of Greenhouse Gas Emissions,Methane Emission,CO2 Emissions,State Biomass Generation,State Transportation Generation
0,x,NAMEPCAP,STCH4AN,STCO2AN,STGENABM,STGENACY
1,Alaska,"3,439","398,059","2,932,683","43,017","4,506,581"
2,Alabama,"38,354","9,884,812","65,211,148","3,335,246","95,467,155"
3,Arkansas,"19,536","6,322,493","33,717,770","1,369,828","43,389,085"
4,Arizona,"40,135","7,318,405","50,682,560","214,378","64,852,172"

In [54]:
methane2_df = methane1_df.iloc[1:]
methane2_df.head()

,State,Tons of Greenhouse Gas Emissions,Methane Emission,CO2 Emissions,State Biomass Generation,State Transportation Generation
1,Alaska,"3,439","398,059","2,932,683","43,017","4,506,581"
2,Alabama,"38,354","9,884,812","65,211,148","3,335,246","95,467,155"
3,Arkansas,"19,536","6,322,493","33,717,770","1,369,828","43,389,085"
4,Arizona,"40,135","7,318,405","50,682,560","214,378","64,852,172"
5,California,"106,793","5,081,974","44,648,567","6,122,047","105,532,221"

In [55]:
methane2_df.dtypes

State                               object
Tons of Greenhouse Gas Emissions    object
Methane Emission                    object
CO2 Emissions                       object
State Biomass Generation            object
State Transportation Generation     object
dtype: object

In [56]:
methane2_df.to_csv("./resources/methane_df.csv", header=True, index=True)

In [57]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [58]:
engine = create_engine("sqlite:///resources/state_emission1.sqlite")

methane2_df.to_sql('state_emission', engine, if_exists='replace', index = True)