In [49]:
import pandas as pd
import numpy as np

In [50]:
methane_load = "resources/total ghgi .csv"
methane_data = pd.read_csv(methane_load)

In [51]:
methane_df = methane_data

In [52]:
methane_df.head()

,State abbreviation,FIPS State code,State nameplate capacity (MW),State annual heat input from combustion (MMBtu),State ozone season heat input from combustion (MMBtu),State total annual heat input (MMBtu),State total ozone season heat input (MMBtu),State annual net generation (MWh),State ozone season net generation (MWh),State annual NOx emissions (tons),...,State wind generation percent (resource mix),State solar generation percent (resource mix),State geothermal generation percent (resource mix),State other fossil generation percent (resource mix),State other unknown/ purchased fuel generation percent (resource mix),State total nonrenewables generation percent (resource mix),State total renewables generation percent (resource mix),State total nonhydro renewables generation percent (resource mix),State total combustion generation percent (resource mix),State total noncombustion generation percent (resource mix)
0,PSTATABB,FIPSST,NAMEPCAP,STHTIAN,STHTIOZ,STHTIANT,STHTIOZT,STNGENAN,STNGENOZ,STNOXAN,...,STWIPR,STSOPR,STGTPR,STOFPR,STOPPR,STTNPR,STTRPR,STTHPR,STCYPR,STCNPR
1,AK,02,"3,439","42,553,081","16,236,971","59,433,354","22,529,498","6,335,034","2,406,057","21,008",...,2.7,0.0,0.0,0.0,0.0,70.4,29.5,3.4,71.1,28.9
2,AL,01,"38,354","824,393,497","395,164,798","1,310,962,923","593,145,427","142,863,240","64,618,103","29,881",...,0.0,0.0,0.0,0.0,0.0,92.4,7.6,2.4,66.8,33.2
3,AR,05,"19,536","387,648,456","187,652,732","561,261,411","267,815,481","60,445,059","28,838,751","27,940",...,0.0,0.0,0.0,0.0,0.0,91.7,8.3,2.3,71.8,28.2
4,AZ,04,"40,135","602,858,094","315,929,076","1,047,151,854","506,075,202","108,734,631","53,847,909","33,982",...,0.5,3.4,0.0,0.0,0.0,89.2,10.8,4.1,59.6,40.4

In [53]:
state_abrv = methane_df["State abbreviation"]
state_annual = methane_df["State total annual heat input (MMBtu)"]
state_total_ozone = methane_df["State total ozone season heat input (MMBtu)"]
state_net = methane_df["State annual net generation (MWh)"]
state_net_ozone = methane_df["State ozone season net generation (MWh)"]
state_input = methane_df["State annual heat input from combustion (MMBtu)"]
state_ozone = methane_df["State ozone season heat input from combustion (MMBtu)"]
state_emission = methane_df["State annual CH4 emissions (lbs)"]
state_biomass = methane_df["State annual biomass net generation (MWh)"]



methane_data_df = pd.DataFrame({
    
    "State": state_abrv,
    "Annual Heat": state_annual,
    "Annual Ozone Input": state_total_ozone,
    "Annual Heat Input from Combustion": state_input,
    "Annual Ozone Input from Combustion": state_ozone,
    "Annual Net Generation": state_net,
    "Annual Net Ozone Generation": state_net_ozone,
    "Methane Emission": state_emission,
    "Biomass Generation": state_biomass
})


methane1_df = methane_data_df[["State", "Annual Heat", "Annual Ozone Input", "Annual Net Generation", "Annual Net Ozone Generation","Annual Heat Input from Combustion", "Annual Ozone Input from Combustion", "Methane Emission", "Biomass Generation"]]
methane1_df.head()

,State,Annual Heat,Annual Ozone Input,Annual Net Generation,Annual Net Ozone Generation,Annual Heat Input from Combustion,Annual Ozone Input from Combustion,Methane Emission,Biomass Generation
0,PSTATABB,STHTIANT,STHTIOZT,STNGENAN,STNGENOZ,STHTIAN,STHTIOZ,STCH4AN,STGENABM
1,AK,"59,433,354","22,529,498","6,335,034","2,406,057","42,553,081","16,236,971","398,059","43,017"
2,AL,"1,310,962,923","593,145,427","142,863,240","64,618,103","824,393,497","395,164,798","9,884,812","3,335,246"
3,AR,"561,261,411","267,815,481","60,445,059","28,838,751","387,648,456","187,652,732","6,322,493","1,369,828"
4,AZ,"1,047,151,854","506,075,202","108,734,631","53,847,909","602,858,094","315,929,076","7,318,405","214,378"

In [54]:
methane1_df.set_index("State", inplace=True)
methane1_df.head()

,Annual Heat,Annual Ozone Input,Annual Net Generation,Annual Net Ozone Generation,Annual Heat Input from Combustion,Annual Ozone Input from Combustion,Methane Emission,Biomass Generation
State,,,,,,,,
PSTATABB,STHTIANT,STHTIOZT,STNGENAN,STNGENOZ,STHTIAN,STHTIOZ,STCH4AN,STGENABM
AK,"59,433,354","22,529,498","6,335,034","2,406,057","42,553,081","16,236,971","398,059","43,017"
AL,"1,310,962,923","593,145,427","142,863,240","64,618,103","824,393,497","395,164,798","9,884,812","3,335,246"
AR,"561,261,411","267,815,481","60,445,059","28,838,751","387,648,456","187,652,732","6,322,493","1,369,828"
AZ,"1,047,151,854","506,075,202","108,734,631","53,847,909","602,858,094","315,929,076","7,318,405","214,378"

In [55]:
methane1_df.to_csv("./resources/methane_df.csv", header=True, index=True)

In [56]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [57]:
engine = create_engine("sqlite:///resources/state_emission.sqlite")

methane1_df.to_sql('state_emission', engine, if_exists='replace', index = True)